name: rag_milvus
channels:
  - conda-forge
dependencies:
  - python=3.13.11
  - pip
  - pip:
      - langchain
      - langchain-ollama
      - pymilvus==2.5.18
      - langchain-milvus==0.2.2
      - milvus-lite
      - langchain-community
      - langchain-openai
      - pypdf
      - fastapi
      - uvicorn
      - unstructured
      - python-multipart
      - langchain-chroma
      - chromadb
